# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'dbcli/tap'
tap 'ellie/atuin'

# Binaries
brew 'autojump'
brew 'cloc'
brew 'fzf'
brew 'git'
brew 'git-lfs'
brew 'git-extras'
brew 'git-secrets'
brew 'gh'
brew 'node'
brew 'neovim'
brew 'poetry'
brew 'pyenv'
brew 'rustup'
brew 'starship'
brew 'make'
brew 'bat'
brew 'yarn'
brew 'zsh'
brew 'ffmpeg'
brew 'ktlint'
brew 'mas'
brew 'dive'
brew 'sheldon'
brew 'wget'
brew 'terraform'
brew 'telnet'
brew 'shellcheck'
brew 'ripgrep'
brew 'rustup-init'
brew 'zoxide'
brew 'pgcli'
brew 'protobuf'
brew 'svn'
brew 'nvm'
brew 'pnpm'
brew 'fd'
brew 'atuin'

# Apps
cask 'docker'
cask 'figma'
cask 'slack'
cask 'signal'
cask 'visual-studio-code'
cask 'raycast'
cask 'obsidian'
cask 'whatsapp'
cask 'iterm2'
cask 'spotify'
cask 'browserosaurus'
cask 'cleanmymac'
cask 'iina'
cask 'mediahuman-audio-converter'
cask 'minecraft'
cask 'monitorcontrol'
cask 'ngrok'
cask 'transmission'
cask 'google-chrome'
cask 'linear-linear'
cask 'toggl-track'
cask 'jetbrains-toolbox'
cask 'notion'
cask 'netnewswire'

# Quicklook
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-mulish'
cask 'font-fira-code'
cask 'font-source-sans-pro'
cask 'font-inter'

# Mac apps
mas "Userscripts", id: 1463298887
mas "Raivo OTP", id: 1498497896
mas "Tailscale", id: 1475387142
