# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

# Binaries
brew 'autojump'
brew 'cloc'
brew 'fzf'
brew 'git'
brew 'git-lfs'
brew 'git-extras'
brew 'gh'
brew 'node'
brew 'neovim'
brew 'poetry'
brew 'pyenv'
brew 'rustup'
brew 'starship'
brew 'make'
brew 'bat'
brew 'yarn'
brew 'zsh'
brew 'ffmpeg'
brew 'ktlint'
brew 'mas'
brew 'dive'
brew 'sheldon'

# Apps
cask '1password'
cask 'docker'
cask 'figma'
cask 'slack'
cask 'signal'
cask 'visual-studio-code'
cask 'raycast'
cask 'obsidian'
cask 'whatsapp'
cask 'iterm2'
cask 'spotify'
cask 'nextdns/tap/nextdns'
cask 'browserosaurus'
cask 'cleanmymac'
cask 'zoom'
cask 'paw'
cask 'iina'
cask 'mediahuman-audio-converter'
cask 'iterm2'
cask 'minecraft'
cask 'monitorcontrol'
cask 'zotero'
cask 'eul'
cask 'privileges'

# Quicklook
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-mulish'
cask 'font-fira-code'
cask 'font-source-sans-pro'
cask 'font-inter'

# Mac apps
mas "Userscripts", id: 1463298887
mas "Raivo OTP", id: 1498497896
