format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$rust\
$nodejs\
$time\
$shell\
$line_break\
$character
"""

[character]
success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"
vicmd_symbol = "[→](bold green)"

[time]
disabled = false
