format="""
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$rust\
$time\
$shell\
$line_break\
$character
"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[➜](bold green)"

[time]
disabled = false

[git_metrics]
disabled = false
added_style = "bold green"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '