# Sheldon configuration file
#
# See https://sheldon.cli.rs

shell = "zsh"

[templates]
defer = """{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}{{ hooks?.post | nl }}"""

# Sourced
# ----------------

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.edit-command-line]
inline = "autoload -Uz edit-command-line && zle -N edit-command-line"

[plugins.sdkman]
inline = '''export SDKMAN_DIR=$(brew --prefix sdkman-cli)/libexec; [[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"'''

# Deferred plugins
# ----------------

[plugins.path]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.aliases]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.compinit]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-auto-notify]
github = "MichaelAquilina/zsh-auto-notify"
use = ["auto-notify.plugin.zsh"]
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zellij-tabula]
github = "bezbac/zellij-tabula"
use = ["{{ name }}.plugin.zsh"]
tag = "v0.2.0"
apply = ["defer"]
