# Sheldon configuration file
#
# See https://sheldon.cli.rs

shell = "zsh"

[templates]
defer = """{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}{{ hooks?.post | nl }}"""

# Sourced
# ----------------

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.path]
local = "~/.zsh/plugins"
apply = ["defer"]

# Deferred plugins
# ----------------

[plugins.aliases]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zellij]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.edit-command-line]
inline = "autoload -Uz edit-command-line && zle -N edit-command-line"
